# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coolcraig' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coolcraig

end

target 'coolcraig WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coolcraig WatchKit App
  pod 'Firebase'

end

target 'coolcraig WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coolcraig WatchKit Extension

end
